### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by amkalenyk** [amkalenyk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by KaTolyk** [comment]
https://www.instagram.com/realDonaldTrump/
https://twitter.com/realDonaldTrump
https://www.facebook.com/DonaldTrump
realDonaldTrump@whitehouse.gov

**Comment by amkalenyk** [comment]
Awesome
